services:
  - type: web
    name: realtradenews
    env: docker
    dockerfilePath: ./Dockerfile
    dockerContext: ./
    port: 3000
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
